import './globals.css'
import { Montserrat  } from 'next/font/google'

const montserrat = Montserrat ({
   weight: ['400', '500', '600', '700'],
   subsets: ['latin'] 
  });

export const metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} w-full h-full text-white bg-gray-800 flex justify-center items-center p-8`}>{children}</body>
    </html>
  )
}
