import {WiNightClear, WiDayHaze, WiNightPartlyCloudy, WiDaySunnyOvercast, WiFog, WiRaindrops, WiRain, WiRainWind, WiRainMix, WiNightThunderstorm, WiNightSnowThunderstorm} from "react-icons/wi";

export const weatherCodeComponents = {
    "0": WiNightClear,
    "1": WiDayHaze,
    "2": WiNightPartlyCloudy,
    "3": WiDaySunnyOvercast,
    "45": WiFog,
    "48": WiFog,
    "51": WiRaindrops,
    "53": WiRaindrops,
    "55": WiRain,
    "61": WiRain,
    "63": WiRain,
    "65": WiRainWind,
    "66": WiRainMix,
    "67": WiRainMix,
    "80": WiRain,
    "81": WiRain,
    "82": WiRainWind,
    "95": WiNightSnowThunderstorm,
    "96": WiNightThunderstorm,
    "99": WiNightThunderstorm,
  } 

  export const weatherLabelMap = {
    "0": "Clear sky",
    "1": "Mainly clear",
    "2": "partly cloudy",
    "3": 'overcast',
    "45": 'Fog' ,
    "48": 'rime fog',
    "51": 'Light Drizzle',
    "53": 'moderate Drizzle',
    "55": 'dense Drizzle',
    "61": 'Slight rain',
    "63": 'moderate rain',
    "65": 'Heavy rain',
    "66": "Freezing rain",
    "67": "Heavy Rain",
    "80": 'Slight rain showers',
    "81": 'Moderate rain showers',
    "82": 'Violent rain showers',  
    "95": "Slight thunderstorm",
    "96": "Thunderstorm",
    "99": "Thunderstorm", 
  }